// import * as React from "react";
// import Topbar from "../../topbar/Topbar";
// import Sidebar from "../../sidebar/Sidebar";
// import { DataGrid, GridToolbar } from "@mui/x-data-grid";
// import { Stack, Button, Modal, Box, Typography } from "@mui/material";
// import axios from "axios";

// export default function OUTLET() {
//   const [branches, setBranches] = React.useState([
//     "PUREGOLD PRICE CLUB - LA TRINIDAD BENGUET",
//     "PUREGOLD PRICE CLUB - BAGUIO",
//     "PUREGOLD PRICE CLUB - LAOAG",
//     "PUREGOLD PRICE CLUB (JR.)- OLD CENTRO",
//     "PUREGOLD PRICE CLUB - CONCEPCION TARLAC",
//     "PUREGOLD PRICE CLUB - CABANATUAN",
//     "PUREGOLD PRICE CLUB - ZARAGOZA",
//     "PUREGOLD PRICE CLUB - GAPAN",
//     "PUREGOLD PRICE CLUB - CAPAS",
//     "PUREGOLD PRICE CLUB - CAUAYAN ISABELA",
//     "PUREGOLD PRICE CLUB (JR.)- PALM PLAZA",
//     "PUREGOLD PRICE CLUB - PANIQUI",
//     "PUREGOLD PRICE CLUB - PUBLIC MARKET",
//     "PUREGOLD PRICE CLUB - ROXAS ISABELA",
//     "PUREGOLD PRICE CLUB - BALER (N.E)",
//     "PUREGOLD PRICE CLUB - MARIA AURORA",
//     "PUREGOLD PRICE CLUB - TUMAUINI",
//     "PUREGOLD PRICE CLUB (EXTRA.)- TUGUEGARAO",
//     "PUREGOLD PRICE CLUB - CENTRO SANTIAGO",
//     "PUREGOLD PRICE CLUB - VICTORY NORTE SANTIAGO (N.E)",
//     "PUREGOLD PRICE CLUB - VIGAN",
//     "PUREGOLD PRICE CLUB - BURNHAM PARK",
//     "PUREGOLD PRICE CLUB (JR.)- BAKAKENG",
//     "PUREGOLD PRICE CLUB - LA UNION",
//     "PUREGOLD PRICE CLUB - BACNOTAN",
//     "PUREGOLD PRICE CLUB - CALASIAO",
//     "PUREGOLD PRICE CLUB - MANAOAG",
//     "PUREGOLD PRICE CLUB - SAN FABIAN",
//     "PUREGOLD PRICE CLUB (JR.)- BONUAN",
//     "PUREGOLD PRICE CLUB - MAYOMBO",
//     "PUREGOLD PRICE CLUB (JR.)- BAYAMBANG",
//     "PUREGOLD PRICE CLUB - VILLASIS",
//     "PUREGOLD PRICE CLUB - TALAVERA",
//     "PUREGOLD PRICE CLUB - SAN JOSE NUEVA ECIJA (N.E)",
//     "PUREGOLD PRICE CLUB - ZULUETA (N.E)",
//     "PUREGOLD PRICE CLUB - CABANATUAN PALENGKE (N.E)",
//     "PUREGOLD PRICE CLUB - PACIFIC MALL (N.E)",
//     "PUREGOLD PRICE CLUB - CIRCUMFERENCIAL (N.E)",
//     "PUREGOLD PRICE CLUB - CROSSING (N.E)",
//     "PUREGOLD PRICE CLUB - GUIMBA",
//     "PUREGOLD PRICE CLUB - ILAGAN",
//     "PUREGOLD PRICE CLUB - ALIBAGU",
//     "PUREGOLD PRICE CLUB - APPARI",
//     "PUREGOLD PRICE CLUB - LAL-LO",
//     "PUREGOLD PRICE CLUB - TUAO",
//     "PUREGOLD PRICE CLUB - SOLANA",
//     "PUREGOLD PRICE CLUB - DAU",
//     "PUREGOLD PRICE CLUB - DAU ACCESS ROAD",
//     "PUREGOLD PRICE CLUB (JR.)- DON JUICO",
//     "PUREGOLD PRICE CLUB - MABALACAT",
//     "PUREGOLD PRICE CLUB - MAWAQUE",
//     "PUREGOLD PRICE CLUB - ANGELES",
//     "PUREGOLD PRICE CLUB (JR.)-BALIBAGO",
//     "PUREGOLD PRICE CLUB - CENTRAL TOWN",
//     "PUREGOLD PRICE CLUB - PANDAN",
//     "PUREGOLD PRICE CLUB - SUBIC",
//     "PUREGOLD PRICE CLUB - OLONGAPO",
//     "PUREGOLD PRICE CLUB - CASTILLEJOS",
//     "PUREGOLD PRICE CLUB -DUTY FREE",
//     "PUREGOLD PRICE CLUB - FERTUNA",
//     "PUREGOLD PRICE CLUB - MAGALANG PAMPANGA",
//     "PUREGOLD PRICE CLUB - ANGELES - MAGALANG ROAD EPZA",
//     "PUREGOLD PRICE CLUB - ARAYAT PAMPANGA",
//     "PUREGOLD PRICE CLUB - MEXICO",
//     "PUREGOLD PRICE CLUB -CANDABA",
//     "PUREGOLD PRICE CLUB - DINALUPIHAN",
//     "PUREGOLD PRICE CLUB (JR.)- ORANI",
//     "PUREGOLD PRICE CLUB (JR.)- LUBAO",
//     "PUREGOLD PRICE CLUB (JR.)- GUAGUA",
//     "PUREGOLD PRICE CLUB (EXTRA.)- FLORIDA BLANCA",
//     "PUREGOLD PRICE CLUB (JR.)- PORAC",
//     "PUREGOLD PRICE CLUB - MASANTOL",
//     "PUREGOLD PRICE CLUB (EXTRA.)- MACABEBE",
//     "PUREGOLD PRICE CLUB (JR.)- STO.TOMAS",
//     "PUREGOLD PRICE CLUB - SAN SIMON",
//     "PUREGOLD PRICE CLUB - MARIVELES",
//     "PUREGOLD PRICE CLUB - LIMAY",
//     "PUREGOLD PRICE CLUB - BALANGA",
//     "PUREGOLD PRICE CLUB (JR.)- ABUCAY",
//     "PUREGOLD PRICE CLUB - IBA ZAMBALES",
//     "ROYAL DUTY FREE 1",
//     "ROYAL DUTY FREE 2",
//     "PUREGOLD PRICE CLUB (JR.)- SF 2 CAFÉ FERNANDINO",
//     "PUREGOLD PRICE CLUB - BULAON",
//     "PUREGOLD PRICE CLUB (JR.)- SF 1 DOLORES",
//     "PUREGOLD PRICE CLUB (EXTRA.)- APALIT",
//     "PUREGOLD PRICE CLUB - TUNGKONG MANGGA",
//     "PUREGOLD PRICE CLUB (JR.)- SAPANG PALAY, SAMPOL",
//     "PUREGOLD PRICE CLUB - SAN JOSE DEL MONTE PALMERA",
//     "PUREGOLD PRICE CLUB - MEYCAUAYAN BANGA",
//     "PUREGOLD PRICE CLUB - MALANDAY",
//     "PUREGOLD PRICE CLUB - OBANDO",
//     "PUREGOLD PRICE CLUB - BALIWAG",
//     "PUREGOLD PRICE CLUB - TANGOS BALIWAG",
//     "PUREGOLD PRICE CLUB - DRT HI-WAY (N.E)",
//     "PUREGOLD PRICE CLUB - HAGONOY BULACAN",
//     "PUREGOLD PRICE CLUB - PAOMBONG",
//     "PUREGOLD PRICE CLUB - TABANG GUIGUINTO",
//     "PUREGOLD PRICE CLUB - MALOLOS",
//     "PUREGOLD PRICE CLUB - SAN MIGUEL BULACAN",
//     "PUREGOLD PRICE CLUB - SAN ILDEFONSO",
//     "PUREGOLD PRICE CLUB - VALENZUELA-1",
//     "PUREGOLD PRICE CLUB - ALIW",
//     "PUREGOLD PRICE CLUB - MARILAO PLAZA CECILIA",
//     "PUREGOLD PRICE CLUB (JR.)- CALVARIO",
//     "PUREGOLD PRICE CLUB (JR.)- CAMALIG",
//     "PUREGOLD PRICE CLUB (JR.)- KARUHATAN",
//     "PUREGOLD PRICE CLUB (JR.)- MALINTA",
//     "PUREGOLD PRICE CLUB - PLARIDEL",
//     "PUREGOLD PRICE CLUB - MALOLOS JUNCTION",
//     "PUREGOLD PRICE CLUB - GUINGUINTO BAYAN",
//     "PUREGOLD PRICE CLUB - BULAKAN,BULAKAN",
//     "PUREGOLD PRICE CLUB - STA.MARIA",
//     "PUREGOLD PRICE CLUB (JR.)- PANDI",
//     "PUREGOLD PRICE CLUB - BOCAUE",
//     "PUREGOLD PRICE CLUB - CASA CECILIA",
//     "PUREGOLD PRICE CLUB - LIAS MARILAO",
//     "PUREGOLD PRICE CLUB (JR.)- LOMA DE GATO",
//     "PUREGOLD PRICE CLUB - MUZON",
//     "PUREGOLD PRICE CLUB - PASO DE BLAS",
//     "PUREGOLD PRICE CLUB (JR.)- LIBERTAD",
//     "PUREGOLD PRICE CLUB - LIBERTAD",
//     "PUREGOLD PRICE CLUB - SUCAT",
//     "PUREGOLD PRICE CLUB - MOONWALK",
//     "PUREGOLD MINIMART - DONA SOLEDAD",
//     "PUREGOLD PRICE CLUB - REMANVILLE",
//     "PUREGOLD PRICE CLUB - SOUTHPARK",
//     "PUREGOLD PRICE CLUB (JR.)- BF HOMES",
//     "PUREGOLD PRICE CLUB - AGUIRRE",
//     "PUREGOLD PRICE CLUB (JR.)- BETTER LIVING",
//     "PUREGOLD PRICE CLUB (JR.)- DOROTEO JOSE",
//     "PUREGOLD PRICE CLUB (JR.)- CARRIEDO",
//     "PUREGOLD PRICE CLUB (JR.)- ESPANA",
//     "PUREGOLD PRICE CLUB (JR.)- BUSTILLOS",
//     "PUREGOLD PRICE CLUB - 999",
//     "PUREGOLD PRICE CLUB (JR.)- JUAN LUNA",
//     "PUREGOLD PRICE CLUB - DIVISORIA",
//     "PUREGOLD PRICE CLUB - MALATE",
//     "PUREGOLD PRICE CLUB - PACO",
//     "PUREGOLD PRICE CLUB - PASIG",
//     "PUREGOLD PRICE CLUB - TAGUIG",
//     "PUREGOLD PRICE CLUB - PARANAQUE-1",
//     "PUREGOLD PRICE CLUB (JR.)- BACLARAN",
//     "PUREGOLD PRICE CLUB - MAKATI-1",
//     "PUREGOLD PRICE CLUB (EXTRA.)- OSMENA",
//     "PUREGOLD PRICE CLUB - SAN ANTONIO",
//     "PUREGOLD PRICE CLUB - SAN DIONISIO",
//     "PUREGOLD PRICE CLUB (JR.)- PANDACAN",
//     "PUREGOLD PRICE CLUB (JR.)- BOCOBO",
//     "PUREGOLD PRICE CLUB - FTI",
//     "PUREGOLD PRICE CLUB (JR.)- TIPAS",
//     "PUREGOLD PRICE CLUB (JR.)- USUSAN",
//     "PUREGOLD PRICE CLUB (EXTRA.)- TAGUIG HAGONOY",
//     "PUREGOLD PRICE CLUB - TAYUMAN-1",
//     "PUREGOLD PRICE CLUB - GAGALANGIN",
//     "PUREGOLD PRICE CLUB - DV HERBOSA",
//     "PUREGOLD PRICE CLUB (JR.)- ZURBARAN",
//     "PUREGOLD PRICE CLUB (JR.)- 3RD AVE",
//     "PUREGOLD PRICE CLUB (JR.)- BLUMENTRITT CGH",
//     "PUREGOLD PRICE CLUB - BLUMENTRITT",
//     "PUREGOLD PRICE CLUB - SOUTHGATE",
//     "PUREGOLD PRICE CLUB (JR.)- V. MAPA",
//     "PUREGOLD PRICE CLUB (JR.)- PUREZA",
//     "PUREGOLD PRICE CLUB - STA.MESA",
//     "PUREGOLD PRICE CLUB - AGORA",
//     "PUREGOLD PRICE CLUB - PULANG LUPA",
//     "PUREGOLD PRICE CLUB - LAS PINAS",
//     "PUREGOLD PRICE CLUB (JR.)- ZAPOTE ARCADE",
//     "PUREGOLD PRICE CLUB - PULANG LUPA UNO",
//     "PUREGOLD PRICE CLUB - MOLITO",
//     "PUREGOLD PRICE CLUB - PUTATAN",
//     "PUREGOLD PRICE CLUB - CASIMIRO",
//     "PUREGOLD PRICE CLUB - MARCOS ALVAREZ LAS PINAS",
//     "PUREGOLD PRICE CLUB - MINDANAO AVE",
//     "PUREGOLD PRICE CLUB - COMMONWEALTH-1",
//     "PUREGOLD PRICE CLUB - NORTH COMMONWEALTH",
//     "PUREGOLD PRICE CLUB - CALOOCAN",
//     "PUREGOLD PRICE CLUB - MONUMENTO",
//     "PUREGOLD PRICE CLUB - BALINTAWAK",
//     "PUREGOLD PRICE CLUB (JR.)- KALAYAAN",
//     "PUREGOLD PRICE CLUB - KANLAON",
//     "PUREGOLD PRICE CLUB (JR.)- DEL MONTE",
//     "PUREGOLD PRICE CLUB (EXTRA.)- A. BONIFACIO",
//     "PUREGOLD PRICE CLUB - MAYPAJO",
//     "PUREGOLD PRICE CLUB - MALABON",
//     "PUREGOLD PRICE CLUB - NAVOTAS",
//     "PUREGOLD PRICE CLUB - CUBAO-1",
//     "PUREGOLD PRICE CLUB - Q.I -1",
//     "PUREGOLD PRICE CLUB (JR.)- MOTHER IGNACIA",
//     "PUREGOLD PRICE CLUB (JR.)- TIMOG",
//     "PUREGOLD PRICE CLUB - Q. AVE",
//     "PUREGOLD PRICE CLUB (JR.)- WEST AVE.",
//     "PUREGOLD PRICE CLUB (EXTRA)- PHILAM",
//     "PUREGOLD PRICE CLUB (EXTRA.)- TANDANG SORA",
//     "PUREGOLD PRICE CLUB - BAESA",
//     "PUREGOLD PRICE CLUB - CROSSROAD",
//     "PUREGOLD PRICE CLUB - LANGARAY",
//     "PUREGOLD PRICE CLUB (MINIMART.)- LIBIS",
//     "PUREGOLD PRICE CLUB - 999 CALOOCAN",
//     "AYAGOLD UP TOWN",
//     "AYAGOLD NORTH VERTIS",
//     "PUREGOLD PRICE CLUB (JR.)- DON ANTONIO",
//     "PUREGOLD PRICE CLUB - CULIAT",
//     "PUREGOLD PRICE CLUB (JR.)- BALARA",
//     "PUREGOLD PRICE CLUB - VISAYAS",
//     "PUREGOLD PRICE CLUB (JR.)- QUIRINO HI WAY",
//     "PUREGOLD PRICE CLUB - TERRACES",
//     "PUREGOLD PRICE CLUB - ZABARTE",
//     "PUREGOLD PRICE CLUB - SUSANO",
//     "PUREGOLD PRICE CLUB - NITANG",
//     "PUREGOLD PRICE CLUB - BAGONG SILANG",
//     "PUREGOLD PRICE CLUB - DEPARO",
//     "PUREGOLD PRICE CLUB - LANGIT ROAD",
//     "PUREGOLD PRICE CLUB - NOVALICHES",
//     "PUREGOLD PRICE CLUB (JR.)- ZABARTE",
//     "PUREGOLD PRICE CLUB - CAMARIN",
//     "PUREGOLD PRICE CLUB - CHAMPACA",
//     "PUREGOLD PRICE CLUB -SUPERPALENGKE, ANTIPOLO (G)",
//     "PUREGOLD PRICE CLUB - AMPID SAN MATEO (G)",
//     "PUREGOLD PRICE CLUB (EXTRA.)- AMPID",
//     "PUREGOLD PRICE CLUB (EXTRA.)- GUITNANG BAYAN",
//     "PUREGOLD PRICE CLUB - SAN RAFAEL",
//     "PUREGOLD PRICE CLUB (JR.)- DULONG BAYAN SAN MATEO",
//     "PUREGOLD PRICE CLUB - BURGOS",
//     "PUREGOLD PRICE CLUB (JR.)- ROSARIO",
//     "PUREGOLD PRICE CLUB (JR.)- DE CASTRO",
//     "PUREGOLD PRICE CLUB - CONCEPCION",
//     "PUREGOLD PRICE CLUB (JR.)- MARIKINA",
//     "PUREGOLD PRICE CLUB - TAYTAY",
//     "PUREGOLD PRICE CLUB - Q. PLAZA",
//     "PUREGOLD PRICE CLUB - JUNCTION",
//     "PUREGOLD PRICE CLUB - BINANGONAN",
//     "PUREGOLD PRICE CLUB - TAYTAY -2",
//     "PUREGOLD PRICE CLUB (JR.)- TAYTAY PALENGKE",
//     "PUREGOLD PRICE CLUB (JR.)- TAYTAY ANNEX",
//     "PUREGOLD PRICE CLUB - SUMULONG",
//     "PUREGOLD PRICE CLUB (JR.)- LILAC",
//     "PUREGOLD PRICE CLUB (EXTRA.)- PANORAMA",
//     "PUREGOLD PRICE CLUB - AYALA MALL MARIKINA",
//     "PUREGOLD PRICE CLUB (EXTRA.)- PARANG",
//     "PUREGOLD PRICE CLUB (JR.)- CONCEPCION",
//     "PUREGOLD PRICE CLUB (EXTRA.)- STA. ELENA",
//     "PUREGOLD PRICE CLUB - ORTIGAS AVE EXT PASIG (G)",
//     "PUREGOLD PRICE CLUB - LIGAYA",
//     "PUREGOLD PRICE CLUB (JR.)- ORTIGAS EXT EAST SUMMIT",
//     "PUREGOLD PRICE CLUB (EXTRA) - BROOKSIDE CAINTA",
//     "PUREGOLD PRICE CLUB (JR.)- PAROLA",
//     "PUREGOLD PRICE CLUB - TAYTAY FLOODWAY",
//     "PUREGOLD PRICE CLUB - MONTALBAN",
//     "PUREGOLD PRICE CLUB - SAN MATEO BANABA",
//     "PUREGOLD PRICE CLUB - ANGONO",
//     "PUREGOLD PRICE CLUB (EXTRA.)- ANGONO HIGH WAY",
//     "PUREGOLD PRICE CLUB (EXTRA.)- ANGONO BAYAN",
//     "PUREGOLD PRICE CLUB - TANAY",
//     "PUREGOLD PRICE CLUB - ANTIPOLO",
//     "PUREGOLD PRICE CLUB (JR.)- ANTIPOLO",
//     "PUREGOLD PRICE CLUB - EXTRA COGEO",
//     "PUREGOLD PRICE CLUB - EASTLAND",
//     "PUREGOLD PRICE CLUB - CIRCUMFERENTIAL ROAD",
//     "PUREGOLD PRICE CLUB - TERESA",
//     "PUREGOLD PRICE CLUB - C. RAYMUNDO",
//     "PUREGOLD PRICE CLUB (JR.)- MALINAO PASIG",
//     "PUREGOLD PRICE CLUB (JR.)- MERCEDEZ",
//     "PUREGOLD PRICE CLUB (JR.)- NANGKA",
//     "PUREGOLD PRICE CLUB (JR.)- BATASAN",
//     "PUREGOLD PRICE CLUB - KALENTONG",
//     "PUREGOLD PRICE CLUB - SHAW",
//     "PUREGOLD PRICE CLUB - STA.ROSA BALIBAGO",
//     "PUREGOLD PRICE CLUB - VICTORY MALL",
//     "PUREGOLD PRICE CLUB - TAGAPO",
//     "PUREGOLD PRICE CLUB - SAN PABLO",
//     "PUREGOLD PRICE CLUB - STA. CRUZ (G)",
//     "PUREGOLD PRICE CLUB - VICTORIA LAGUNA",
//     "PUREGOLD PRICE CLUB (MINIMART.)- PILA",
//     "PUREGOLD PRICE CLUB - HALANG",
//     "PUREGOLD PRICE CLUB - PAGSANJAN",
//     "PUREGOLD PRICE CLUB - FAMY",
//     "PUREGOLD PRICE CLUB - STA.ROSA BAYAN (G)",
//     "PUREGOLD PRICE CLUB - ALAMINOS",
//     "PUREGOLD PRICE CLUB - ROXAS MINDORO",
//     "PUREGOLD PRICE CLUB - PACITA",
//     "PUREGOLD PRICE CLUB (MINIMART.)- VILLA OLYMPIA",
//     "PUREGOLD PRICE CLUB (MINIMART.)- MAGSAYSAY",
//     "PUREGOLD PRICE CLUB - BINAN",
//     "PUREGOLD PRICE CLUB (EXTRA.)- GOLDEN CITY",
//     "PUREGOLD PRICE CLUB (JR.)- CROSSTOWN",
//     "PUREGOLD PRICE CLUB (JR.)- LOS BANOS",
//     "PUREGOLD PRICE CLUB (EXTRA.)- LOS BANOS",
//     "PUREGOLD PRICE CLUB (JR.)- PARIAN",
//     "PUREGOLD PRICE CLUB - SAN ISIDRO CABUYAO",
//     "PUREGOLD PRICE CLUB (JR.)- CANLUBANG",
//     "PUREGOLD PRICE CLUB (EXTRA.)- CANLUBANG",
//     "PUREGOLD PRICE CLUB (EXTRA.)- MAMATID",
//     "PUREGOLD PRICE CLUB (EXTRA.)- CABUYAO BANLIC",
//     "PUREGOLD PRICE CLUB - CROSSING CALAMBA",
//     "PUREGOLD PRICE CLUB - CALAMBA BAYAN",
//     "PUREGOLD PRICE CLUB - CALIHAN HIGHWAY",
//     "PUREGOLD PRICE CLUB (EXTRA.)- SAN PABLO",
//     "PUREGOLD PRICE CLUB - CANDELARIA",
//     "PUREGOLD PRICE CLUB (EXTRA.)- TIAONG",
//     "PUREGOLD PRICE CLUB (JR.)- SAN JUAN BATANGAS",
//     "PUREGOLD PRICE CLUB - ROSARIO BATANGAS",
//     "PUREGOLD PRICE CLUB - LIPA",
//     "PUREGOLD PRICE CLUB - TANAUAN",
//     "PUREGOLD PRICE CLUB - STO.TOMAS BATANGAS",
//     "PUREGOLD PRICE CLUB - CALAUAN",
//     "PUREGOLD PRICE CLUB - NEW MARKET BATANGAS (G)",
//     "PUREGOLD PRICE CLUB - CALICANTO",
//     "PUREGOLD PRICE CLUB - BOAC MARINDUQUE",
//     "PUREGOLD PRICE CLUB - LUCENA",
//     "PUREGOLD PRICE CLUB - TANZA",
//     "PUREGOLD PRICE CLUB - CARMONA",
//     "PUREGOLD PRICE CLUB - GMA",
//     "PUREGOLD PRICE CLUB - BUCANDALA",
//     "PUREGOLD PRICE CLUB - BACOOR",
//     "PUREGOLD PRICE CLUB - ANABU",
//     "PUREGOLD PRICE CLUB (JR.)- PALIPARAN",
//     "PUREGOLD PRICE CLUB (EXTRA.)- MAGDIWANG",
//     "PUREGOLD PRICE CLUB (JR.)- MARCOS ALVAREZ",
//     "PUREGOLD PRICE CLUB - MOLINO BLVD.",
//     "PUREGOLD PRICE CLUB - MOLINO TOWN CENTER",
//     "PUREGOLD PRICE CLUB - MOLINO ROAD",
//     "PUREGOLD PRICE CLUB - NOVELETA OASIS",
//     "PUREGOLD PRICE CLUB - KAWIT",
//     "PUREGOLD PRICE CLUB - ROSARIO",
//     "PUREGOLD PRICE CLUB - NOVELETA",
//     "PUREGOLD PRICE CLUB (EXTRA.)- PRINZA",
//     "PUREGOLD DIVIMART - MANGGAHAN",
//     "PUREGOLD PRICE CLUB (JR.)- HUGO PEREZ",
//     "PUREGOLD DIVIMART - INOCENCIO",
//     "PUREGOLD PRICE CLUB - BROOKSIDE LANE",
//     "PUREGOLD PRICE CLUB (JR.)- GEN TRIAS",
//     "PUREGOLD PRICE CLUB - BUHAY NA TUBIG",
//     "PUREGOLD PRICE CLUB - TERMINAL MALL",
//     "PUREGOLD PRICE CLUB - DASMARINAS HIGH WAY",
//     "PUREGOLD PRICE CLUB (JR.)- DASMA BAYAN",
//     "PUREGOLD PRICE CLUB - TANZANG LUMA",
//     "PUREGOLD PRICE CLUB (JR.)- GOLDEN CITY",
//     "PUREGOLD PRICE CLUB (JR.)- HABAY",
//     "PUREGOLD PRICE CLUB - SILANG",
//     "PUREGOLD PRICE CLUB (JR.)- TAGAYTAY-A",
//     "PUREGOLD PRICE CLUB (EXTRA.)- TAGAYTAY",
//     "PUREGOLD PRICE CLUB (JR.)- NAIC",
//     "PUREGOLD PRICE CLUB - SAN PEDRO",
//     "PUREGOLD PRICE CLUB - LANGGAM",
//     "PUREGOLD PRICE CLUB (JR.)- BINAN",
//     "PUREGOLD PRICE CLUB - BINAN BAYAN",
//     "PUREGOLD PRICE CLUB (EXTRA.)- HALANG",
//     "PUREGOLD PRICE CLUB - DIGOS",
//     "PUREGOLD PRICE CLUB - TAGUM",
//     "PUREGOLD PRICE CLUB - STO.TOMAS",
//     "PUREGOLD PRICE CLUB - LANANG",
//     "PUREGOLD PRICE CLUB - COTABATO MAIN",
//     "PUREGOLD PRICE CLUB - COTABATO FIESTA MALL",
//     "PUREGOLD PRICE CLUB - OZAMIS",
//     "PUREGOLD PRICE CLUB - CAGAYAN DE ORO",
//     "PUREGOLD PRICE CLUB - VALENCIA",
//     "PUREGOLD - ILIGAN",
//     "PUREGOLD PRICE CLUB - BUTUAN",
//     "PUREGOLD PRICE CLUB - LANGIHAN",
//     "PUREGOLD JR. ELVINDA",
//     "PUREGOLD JUNIOR - CABUYAO BAYAN",
//     "PUREGOLD - CALAPAN",
//     "PUREGOLD CROSSING EAST",
//     "PUREGOLD PRICE CLUB - IRIGA",
//     "PUREGOLD PRICE CLUB - PILI",
//     "PUREGOLD PRICE CLUB - NAGA DIVERSION",
//     "PUREGOLD PRICE CLUB - CENTRO NAGA",
//     "PUREGOLD PRICE CLUB - LEGAZPI ALBAY",
//     "PUREGOLD PRICE CLUB - SORSOGON",
//     "PUREGOLD PRICE CLUB - IROSIN SORSOGON",
//     "PUREGOLD PRICE CLUB -GUIHULNGAN",
//     "PUREGOLD PRICE CLUB - LIBERTAD BACOLOD",
//     "PUREGOLD PRICE CLUB (JR.) -CENTROPLEX",
//     "PUREGOLD PRICE CLUB - MANSILINGAN",
//     "PUREGOLD PRICE CLUB -PORT BACOLOD",
//     "PUREGOLD PRICE CLUB -BATA BACOLOD",
//     "PUREGOLD PRICE CLUB -888 CHINA TOWN SQUARE",
//     "PUREGOLD PRICE CLUB -HINIGARAN",
//     "PUREGOLD PRICE CLUB - KABANKALAN",
//     "PUREGOLD PRICE CLUB - BAROTAC VIEJO",
//     "PUREGOLD PRICE CLUB - BAROTAC NUEVO",
//     "PUREGOLD PRICE CLUB - ESCALANTE",
//     "PUREGOLD - CADIZ",
//     "PUREGOLD PRICE CLUB - BURGOS",
//     "PUREGOLD PRICE CLUB - LEGAZPI",
//     "PUREGOLD - PONTEVEDRA ROXAS",
//     "PUREGOLD PRICE CLUB -BAYBAY GOODSHOP",
//     "PUREGOLD PRICE CLUB -PUEBLO DE PANAY",
//     "PUREGOLD PRICE CLUB-OTON",
//     "PUREGOLD - JARO",
//     "PUREGOLD PRICE CLUB - PAVIA",
//     "PUREGOLD PRICE CLUB - STA.BARBARA",
//     "PUREGOLD PRICE CLUB -SAN CARLOS",
//     "PUREGOLD - BAYAWAN",
//     "PUREGOLD - LA CASTELLANA",
//     "PUREGOLD - CANLAON",
//     "PUREGOLD - CALINOG",
//     "PUREGOLD PRICE CLUB - MARASBARAS",
//     "PUREGOLD PRICE CLUB - REAL TACLOBAN",
//     "PUREGOLD PRICE CLUB - CALANIPAWAN",
//     "PUREGOLD PRICE CLUB - KANANGA",
//     "PUREGOLD PRICE CLUB - CARIGARA",
//     "PUREGOLD PRICE CLUB - ABUYOG",
//     "PUREGOLD PRICE CLUB - DULAG",
//     "PUREGOLD PRICE CLUB - ALANG-ALANG",
//     "PUREGOLD PRICE CLUB - PALO",
//     "PUREGOLD PRICE CLUB - BORONGAN",
//     "PUREGOLD PRICE CLUB - PAGASA BINANGONAN",
//     "PUREGOLD PRICE CLUB - DOLORES",
//     "PUREGOLD PRICE CLUB - BAYBAY LEYTE",
//     "PUREGOLD PRICE CLUB - ORMOC",
//     "PUREGOLD PRICE CLUB - SOGOD",
//     "PUREGOLD PRICE CLUB - BATO",
//     "PUREGOLD PRICE CLUB - ABUCAY",
//     "PUREGOLD - MANGO",
//     "PUREGOLD - TALISAY",
//     "PUREGOLD - GUADALUPE",
//     "PUREGOLD- KASAMBAGAN",
//     "PUREGOLD PRICE CLUB - SINDALAN",
//     "AFPCES - BNS C&X NAVAL GATE 3 FORT BONFACIO",
//     "AFPCES - C&X V. LUNA",
//     "AFPCES - FB C&X FORT BONIFACIO",
//     "AFPCES - MAIN C&X MAIN DRUGSTORE CAMP AGUINALDO",
//     "AFPCES - MALACANANG",
//     "GAISANO CAPITAL - CASUNTINGAN",
//     "GAISANO CAPITAL - DANAO",
//     "GAISANO CAPITAL - MACTAN",
//     "GAISANO CAPITAL - OPM",
//     "GAISANO CAPITAL - SAVER'SMART BASAK",
//     "GAISANO CAPITAL - SOUTH",
//     "GAISANO CAPITAL - SRP",
//     "GAISANO CAPITAL - TISA",
//     "GAISANO GRAND - BALAMBAN",
//     "GAISANO GRAND - CARCAR",
//     "GAISANO GRAND - CORDOVA",
//     "GAISANO GRAND - DUMANJUG",
//     "GAISANO GRAND - FIESTA MALL",
//     "GAISANO GRAND - FIESTA MALL 2",
//     "GAISANO GRAND - LILOAN",
//     "GAISANO GRAND - MACTAN",
//     "GAISANO GRAND - MINGLANILLA",
//     "GAISANO GRAND - MOALBOAL",
//     "GAISANO GRAND - NORTH BASAK",
//     "GAISANO GRAND - TALAMBAN",
//     "GAISANO METRO - BANILAD",
//     "GAISANO METRO - CANDUMAN",
//     "GAISANO METRO - COLON",
//     "GAISANO METRO - IT PARK",
//     "GAISANO METRO - MANDAUE",
//     "GAISANO METRO - NAGA",
//     "GAISANO SAVER'SMART - BACAYAN",
//     "GAISANO SAVER'SMART - T.PADILLA",
//     "METRO FRESH N EASY - SHANGRILA",
//     "METRO FRESH N EASY - TABOK",
//     "METRO FRESH N EASY - UMAPAD",
//     "METRO GAISANO - AYALA",
//     "METRO GUN-OB",
//     "METRO LG GARDEN",
//     "SAVEMORE - EMALL",
//     "SAVEMORE - PARKMALL",
//     "SM - CONSOLACION",
//     "SM - INSULAR",
//     "SM - LAPU LAPU",
//     "SM - MACTAN",
//     "SM - MARIBAGO",
//     "SM - SEA SIDE CITY",
//     "SUPER METRO - BOGO",
//     "SUPER METRO - CARCAR",
//     "SUPER METRO - OPON",
//     "SUPER METRO - TOLEDO",
//     "JEREMYS - LEMERY",
//     "RC ALVAREZ - LEMERY",
//     "EVER SANTOLAN",
//     "EVERPLUS SUPERSTORE INC - YUSECO",
//     "EVERPLUS SUPERSTORE INC. - 10TH AVE.",
//     "EVERPLUS SUPERSTORE INC. - 11TH AVE.",
//     "EVERPLUS SUPERSTORE INC. - 4TH STATE",
//     "EVERPLUS SUPERSTORE INC. - ARLEGUI QUIAPO",
//     "EVERPLUS SUPERSTORE INC. - BAESA",
//     "EVERPLUS SUPERSTORE INC. - BAGBAG",
//     "EVERPLUS SUPERSTORE INC. - BAGONG SILANG",
//     "EVERPLUS SUPERSTORE INC. - BAGUMBAYAN",
//     "EVERPLUS SUPERSTORE INC. - BAGUMBONG",
//     "EVERPLUS SUPERSTORE INC. - BANGKAL",
//     "EVERPLUS SUPERSTORE INC. - CAINTA",
//     "EVERPLUS SUPERSTORE INC. - CAVITE",
//     "EVERPLUS SUPERSTORE INC. - COMMONWEALTH",
//     "EVERPLUS SUPERSTORE INC. - CONCEPCION",
//     "EVERPLUS SUPERSTORE INC. - DALANDANAN",
//     "EVERPLUS SUPERSTORE INC. - FOREST HILL",
//     "EVERPLUS SUPERSTORE INC. - GEN.T DE LEON",
//     "EVERPLUS SUPERSTORE INC. - HERMOSA",
//     "EVERPLUS SUPERSTORE INC. - KAYBIGA",
//     "EVERPLUS SUPERSTORE INC. - LANGARAY",
//     "EVERPLUS SUPERSTORE INC. - LORETO MORNING BREEZE",
//     "EVERPLUS SUPERSTORE INC. - MALIGAYA",
//     "EVERPLUS SUPERSTORE INC. - MARULAS",
//     "EVERPLUS SUPERSTORE INC. - MASANGKAY",
//     "EVERPLUS SUPERSTORE INC. - MAYPAJO",
//     "EVERPLUS SUPERSTORE INC. - MAYSAN",
//     "EVERPLUS SUPERSTORE INC. - MUZON",
//     "EVERPLUS SUPERSTORE INC. - NAVOTAS",
//     "EVERPLUS SUPERSTORE INC. - PACO",
//     "EVERPLUS SUPERSTORE INC. - PALIPARAN",
//     "EVERPLUS SUPERSTORE INC. - PANDACAN",
//     "EVERPLUS SUPERSTORE INC. - PANGHULO",
//     "EVERPLUS SUPERSTORE INC. - PARANG",
//     "EVERPLUS SUPERSTORE INC. - PATEROS",
//     "EVERPLUS SUPERSTORE INC. - PEARL DRIVE",
//     "EVERPLUS SUPERSTORE INC. - PEÑAFRANCIA",
//     "EVERPLUS SUPERSTORE INC. - PINAGBUHATAN",
//     "EVERPLUS SUPERSTORE INC. - POLO",
//     "EVERPLUS SUPERSTORE INC. - QUIRINO HIWAY",
//     "EVERPLUS SUPERSTORE INC. - RETIRO",
//     "EVERPLUS SUPERSTORE INC. - ROCES",
//     "EVERPLUS SUPERSTORE INC. - SAN MATEO",
//     "EVERPLUS SUPERSTORE INC. - SAPANG PALAY",
//     "EVERPLUS SUPERSTORE INC. - SAUYO",
//     "EVERPLUS SUPERSTORE INC. - SUCAT",
//     "EVERPLUS SUPERSTORE INC. - TALIPAPA",
//     "EVERPLUS SUPERSTORE INC. - TONDO",
//     "EVERPLUS SUPERSTORE INC. - TRABAJO",
//     "EVERPLUS SUPERSTORE INC. - TRECE",
//     "EVERPLUS SUPERSTORE INC. - VICAS",
//     "EVERPLUS SUPERSTORE INC. - ZAPOTE",
//     "ISETANN - CARRIEDO",
//     "ISETANN - CUBAO",
//     "ISETANN - P. TUAZON",
//     "ISETANN - RECTO",
//     "ISETANN - STA MESA",
//     "LANDMARK - ALABANG",
//     "LANDMARK - MAKATI",
//     "LANDMARK - NUVALI",
//     "LANDMARK - TRINOMA COMPLEX",
//     "LANDMARK - TRINOMA MAIN",
//     "LIANA'S SUPERMARKET - ALABANG",
//     "LIANA'S SUPERMARKET - CALAMBA",
//     "LIANA'S SUPERMARKET - EVACOM",
//     "LIANA'S SUPERMARKET - LEVERIZA",
//     "LIANA'S SUPERMARKET - LRT",
//     "LIANA'S SUPERMARKET - PASIG",
//     "LIANA'S SUPERMARKET - SAMPALOC",
//     "LIANA'S SUPERMARKET - SAN PABLO",
//     "LIANA'S SUPERMARKET - STO TOMAS",
//     "FISHERMALL MALABON",
//     "FISHERMALL Q. AVENUE",
//     "HI-TOP SUPERMARKET - AURORA BLVD",
//     "HI-TOP SUPERMARKET - Q.AVE.",
//     "MAKATI SUP. - ALABANG",
//     "MERRYMART DOUBLE DRAGON",
//     "METRO GAISANO LEGAZPI",
//     "METRO GAISANO NAGA",
//     "METRO LUCENA",
//     "METRO RETAILS STORES GROUP, INC. - ALABANG",
//     "METRO RETAILS STORES GROUP, INC. - ANTIPOLO",
//     "METRO RETAILS STORES GROUP, INC. - BINONDO",
//     "METRO RETAILS STORES GROUP, INC. - FELIZ",
//     "METRO RETAILS STORES GROUP, INC. - GATE3",
//     "METRO RETAILS STORES GROUP, INC. - IMUS",
//     "METRO RETAILS STORES GROUP, INC. - MARKET MARKET",
//     "METRO RETAILS STORES GROUP, INC. - NEW PORT",
//     "METRO RETAILS STORES GROUP, INC. - SHAW",
//     "METRO RETAILS STORES GROUP, INC. - TAGAYTAY",
//     "PIONEER CENTRE",
//     "STA LUCIA - PHASE1",
//     "STA LUCIA - PHASE3",
//     "TROPICAL HUT - BF AGUIRRE",
//     "TROPICAL HUT - FTI",
//     "TROPICAL HUT - PANAY",
//     "TROPICAL HUT - SHAW",
//     "UNIMART - CAPITAL COMMON PASIG",
//     "UNIMART - SAN JUAN",
//     "ROBINSON - ILOCOS",
//     "ROBINSON - NEW VALENCIA",
//     "ROBINSON EASYMART - NOVALICHES",
//     "ROBINSON EASYMART - SACRED HEART",
//     "ROBINSON EASYMART - MARIKINA HEIGHTS",
//     "ROBINSON PLACE - OTIS",
//     "ROBINSONS - 8 FORBES TOWN ROAD TAGUIG",
//     "ROBINSONS - ACACIA ESCALADES PASIG",
//     "ROBINSONS - AL NOR MALL COTABATO",
//     "ROBINSONS - ALBAY 738 LEGAZPI",
//     "ROBINSONS - ALICIA",
//     "ROBINSONS - ANTIQUE",
//     "ROBINSONS - BACOLOD TRIANGLE",
//     "ROBINSONS - BALAGTAS",
//     "ROBINSONS - BALANGA",
//     "ROBINSONS - BANAWE",
//     "ROBINSONS - BANILAD CEBU",
//     "ROBINSONS - BASELINE",
//     "ROBINSONS - BF AGUIRRE",
//     "ROBINSONS - BIGNAY VALENZUELA",
//     "ROBINSONS - BLUEWAVE MARIKINA",
//     "ROBINSONS - BUCANDALA",
//     "ROBINSONS - C3 MALL PAGADIAN",
//     "ROBINSONS - CALAPAN",
//     "ROBINSONS - CALIFORNIA MANDALUYONG",
//     "ROBINSONS - CAPITOL",
//     "ROBINSONS - CASIMIRA",
//     "ROBINSONS - CENTRO MALL CABUYAO",
//     "ROBINSONS - CITIMALL ROXAS",
//     "ROBINSONS - CLOVERLEAF MALL",
//     "ROBINSONS - COMMONWEALTH",
//     "ROBINSONS - COMMONWEALTH(shopwise)",
//     "ROBINSONS - CONGRESSIONAL",
//     "ROBINSONS - CYBERGATE DAVAO",
//     "ROBINSONS - DOLORES SAN FERNANDO",
//     "ROBINSONS - DON ANTONIO",
//     "ROBINSONS - DOÑA CARMEN",
//     "ROBINSONS - EASTWOOD TECHNOPLAZA II",
//     "ROBINSONS - EASYMART CABUYAO",
//     "ROBINSONS - EMALL NAGA",
//     "ROBINSONS - FEDERAL BAY GARDEN PASAY",
//     "ROBINSONS - FILINVEST BATASAN HILLS",
//     "ROBINSONS - GALLERIA SOUTH - A",
//     "ROBINSONS - GCC MEXICO",
//     "ROBINSONS - GEEGE MALL OZAMIZ",
//     "ROBINSONS - GRACELAND MALOLOS",
//     "ROBINSONS - GRACELAND PLAZA MARIKINA",
//     "ROBINSONS - GREEN GATE MALAGASANG IMUS",
//     "ROBINSONS - GROTTO",
//     "ROBINSONS - GT PARK PLACE MOLO",
//     "ROBINSONS - GUAGUA TOWNCENTER",
//     "ROBINSONS - GUSA CAGAYAN DE ORO",
//     "ROBINSONS - IMALL CANLUBANG",
//     "ROBINSONS - ISLAND CENTRAL MACTAN",
//     "ROBINSONS - KARANGALAN PASIG",
//     "ROBINSONS - LAVINA PARK VALENCIA",
//     "ROBINSONS - LIMKETKAI MALL CDO",
//     "ROBINSONS - LUCKY GOLD PLAZA ORTIGAS",
//     "ROBINSONS - MADISON GALERIES MUNTINLUPA",
//     "ROBINSONS - MAIN SQUARE MOLINO",
//     "ROBINSONS - MC MALABON",
//     "ROBINSONS - MERCEDES PASIG",
//     "ROBINSONS - METRO PLAZA",
//     "ROBINSONS - METROTOWN TARLAC",
//     "ROBINSONS - MEYCAUAYAN",
//     "ROBINSONS - MINGLANILLA",
//     "ROBINSONS - MONTALBAN TOWNCENTER",
//     "ROBINSONS - NEPOMALL DAGUPAN",
//     "ROBINSONS - NOVALICHES",
//     "ROBINSONS - NUCITI CENTRAL BATANGAS",
//     "ROBINSONS - ONE AYALA",
//     "ROBINSONS - ONE NORTH DAU",
//     "ROBINSONS - OPEN MARKET MANSILINGAN",
//     "ROBINSONS - ORMOC CENTRUM",
//     "ROBINSONS - PACITA",
//     "ROBINSONS - PAVIA",
//     "ROBINSONS - PORTA VAGA MALL BAGUIO",
//     "ROBINSONS - PUEBLO VERDE MACTAN",
//     "ROBINSONS - PULILAN",
//     "ROBINSONS - QUIRINO HI WAY LAGRO",
//     "ROBINSONS - ROXAS MINDORO",
//     "ROBINSONS - SAN CARLOS TOWN CENTER PANGASINAN",
//     "ROBINSONS - SOUTH TOWN CENTER TABUNOK",
//     "ROBINSONS - SOUTHPARK MALL ALABANG",
//     "ROBINSONS - SOUTHWOODS MALL LAGUNA",
//     "ROBINSONS - SPARK CUBAO",
//     "ROBINSONS - SUMMIT RIDGE TAGAYTAY",
//     "ROBINSONS - SUSANO COMPLEX NOVALICHES",
//     "ROBINSONS - TALAMBAN TIME SQUARE CEBU",
//     "ROBINSONS - TALAVERA SQUARE ILAGAN",
//     "ROBINSONS - TALISAY CEBU",
//     "ROBINSONS - TAMBO LIPA",
//     "ROBINSONS - TANDANG SORA",
//     "ROBINSONS - TAÑEDO TARLAC",
//     "ROBINSONS - TARGETMALL STA. ROSA",
//     "ROBINSONS - TIMOG",
//     "ROBINSONS - TOWNVILLE ABREEZA DAVAO",
//     "ROBINSONS - TOWNVILLE ARVO DASMARINAS",
//     "ROBINSONS - TOWNVILLE BF PARANAQUE",
//     "ROBINSONS - TOWNVILLE BUHAY NA TUBIG",
//     "ROBINSONS - TOWNVILLE CABANATUAN",
//     "ROBINSONS - TOWNVILLE NUVALI STA ROSA - A",
//     "ROBINSONS - TOWNVILLE PERDICES DGT",
//     "ROBINSONS - TOWNVILLE REGALADO FAIRVIEW",
//     "ROBINSONS - TUTUBAN CENTERMALL",
//     "ROBINSONS - TWINLAKES VILLAGE BATANGAS",
//     "ROBINSONS - VALENZUELA",
//     "ROBINSONS - VENICE GRAND MCKINLEY",
//     "ROBINSONS - VICTORY MALL",
//     "ROBINSONS - VILLAMONTE",
//     "ROBINSONS - WOODSVILLE MERVILLE",
//     "ROBINSONS - XENTRO MALL LEMERY BATANGAS - A",
//     "ROBINSONS - XENTRO MALL VIGAN",
//     "ROBINSONS - XEVERA MABALACAT",
//     "ROBINSONS - ZABARTE",
//     "ROBINSONS EASYMART - ALABANG HILLS",
//     "ROBINSONS EASYMART - ALIMA BAY BACOOR",
//     "ROBINSONS EASYMART - ARBORTOWNE VALENZUELA",
//     "ROBINSONS EASYMART - ARNAIZ",
//     "ROBINSONS EASYMART - BAGONG KALSADA",
//     "ROBINSONS EASYMART - BALER",
//     "ROBINSONS EASYMART - BAMBAN TARLAC",
//     "ROBINSONS EASYMART - BARAS",
//     "ROBINSONS EASYMART - BASAK",
//     "ROBINSONS EASYMART - BETTERLIVING",
//     "ROBINSONS EASYMART - BONI",
//     "ROBINSONS EASYMART - BUHAY NA TUBIG",
//     "ROBINSONS EASYMART - CABAHUG",
//     "ROBINSONS EASYMART - CALACA",
//     "ROBINSONS EASYMART - CALAMBA",
//     "ROBINSONS EASYMART - CALUMPIT",
//     "ROBINSONS EASYMART - CAPITOL",
//     "ROBINSONS EASYMART - CASA ALSELMO MALOLOS",
//     "ROBINSONS EASYMART - CONCEPCION TARLAC",
//     "ROBINSONS EASYMART - CROWN BLDG. STO. TOMAS",
//     "ROBINSONS EASYMART - CULIAT",
//     "ROBINSONS EASYMART - CUTCUT",
//     "ROBINSONS EASYMART - DAHLIA",
//     "ROBINSONS EASYMART - E. RODRIGUEZ SR. QC (PURITY)",
//     "ROBINSONS EASYMART - EPL",
//     "ROBINSONS EASYMART - FAIRVIEW",
//     "ROBINSONS EASYMART - FARMERS",
//     "ROBINSONS EASYMART - FIL AM",
//     "ROBINSONS EASYMART - GENERAL AVENUE",
//     "ROBINSONS EASYMART - GUAGUA",
//     "ROBINSONS EASYMART - GUIMBA NUEVA ECIJA",
//     "ROBINSONS EASYMART - GUN-OB",
//     "ROBINSONS EASYMART - HAGONOY",
//     "ROBINSONS EASYMART - HARMONY",
//     "ROBINSONS EASYMART - HERMANOS SAN PABLO",
//     "ROBINSONS EASYMART - HERMOSA",
//     "ROBINSONS EASYMART - HILARIO SAN PABLO",
//     "ROBINSONS EASYMART - HILL SIDE",
//     "ROBINSONS EASYMART - HOLIDAY ISLAND B.SILANG",
//     "ROBINSONS EASYMART - HOMES ANTIPOLO",
//     "ROBINSONS EASYMART - KAMBAL ROAD",
//     "ROBINSONS EASYMART - KAMUNING",
//     "ROBINSONS EASYMART - LAGRO",
//     "ROBINSONS EASYMART - LANCASTER",
//     "ROBINSONS EASYMART - LOYOLA HEIGHTS QC",
//     "ROBINSONS EASYMART - MAGALANG",
//     "ROBINSONS EASYMART - MAGINHAWA",
//     "ROBINSONS EASYMART - MAKATI",
//     "ROBINSONS EASYMART - MANHATTAN",
//     "ROBINSONS EASYMART - MARCOS ALVAREZ",
//     "ROBINSONS EASYMART - MARILAO BULACAN",
//     "ROBINSONS EASYMART - MARIPOSA ARCADE KAPASIGAN",
//     "ROBINSONS EASYMART - MARKET CITY",
//     "ROBINSONS EASYMART - MATATALAIB",
//     "ROBINSONS EASYMART - MAYPAJO",
//     "ROBINSONS EASYMART - METRO PLAZA B.SILANG",
//     "ROBINSONS EASYMART - METRO POINT TAFT",
//     "ROBINSONS EASYMART - MIRA NILA",
//     "ROBINSONS EASYMART - MOONWALK LAS PIÑAS",
//     "ROBINSONS EASYMART - MUNOZ NUEVA ECIJA",
//     "ROBINSONS EASYMART - N' DOMINGO",
//     "ROBINSONS EASYMART - NAGA ROAD",
//     "ROBINSONS EASYMART - NAIC CAVITE CITY",
//     "ROBINSONS EASYMART - NEWTOWN MACTAN",
//     "ROBINSONS EASYMART - OLD SAUYO",
//     "ROBINSONS EASYMART - OLONGAPO",
//     "ROBINSONS EASYMART - ORANI BATAAN",
//     "ROBINSONS EASYMART - P TUAZON",
//     "ROBINSONS EASYMART - P. BURGOS CAVITE CITY",
//     "ROBINSONS EASYMART - PAJAC",
//     "ROBINSONS EASYMART - PANDAN",
//     "ROBINSONS EASYMART - PARDO",
//     "ROBINSONS EASYMART - PARIAN",
//     "ROBINSONS EASYMART - PATEROS",
//     "ROBINSONS EASYMART - PEMBO MAKATI",
//     "ROBINSONS EASYMART - PILILLA",
//     "ROBINSONS EASYMART - PIO",
//     "ROBINSONS EASYMART - PITX",
//     "ROBINSONS EASYMART - POBLACION",
//     "ROBINSONS EASYMART - PULUNG CACUTUD",
//     "ROBINSONS EASYMART - RIZAL NUEVA ECIJA",
//     "ROBINSONS EASYMART - ROBLU CAINTA",
//     "ROBINSONS EASYMART - ROOSEVELT",
//     "ROBINSONS EASYMART - SAN FRANCISCO SAN PABLO",
//     "ROBINSONS EASYMART - SAN LORENZO",
//     "ROBINSONS EASYMART - SAN LUCAS SAN PABLO",
//     "ROBINSONS EASYMART - SAN MATEO",
//     "ROBINSONS EASYMART - SAN SEBASTIAN TARLAC",
//     "ROBINSONS EASYMART - SAN SIMON",
//     "ROBINSONS EASYMART - SAN VICENTE TARLAC",
//     "ROBINSONS EASYMART - SANTOLAN",
//     "ROBINSONS EASYMART - SILANG",
//     "ROBINSONS EASYMART - SOLANA",
//     "ROBINSONS EASYMART - STAMFORD",
//     "ROBINSONS EASYMART - STAR HOMES",
//     "ROBINSONS EASYMART - STO TOMAS PASIG",
//     "ROBINSONS EASYMART - TANZA",
//     "ROBINSONS EASYMART - THE EMERALD COURT PROJECT 6",
//     "ROBINSONS EASYMART - THE LINK",
//     "ROBINSONS EASYMART - TOWN CENTER",
//     "ROBINSONS EASYMART - TUMANA",
//     "ROBINSONS EASYMART - AMAIA",
//     "ROBINSONS EASYMART - BF RESORT LP",
//     "ROBINSONS EASYMART - BINANGONAN",
//     "ROBINSONS EASYMART - BIRMINGHAM",
//     "ROBINSONS EASYMART - BLOCK ONE",
//     "ROBINSONS EASYMART - C.RAYMUNDO",
//     "ROBINSONS EASYMART LIGTASAN TARLAC",
//     "ROBINSONS EASYMART - ONE MERCEDES",
//     "ROBINSONS EASYMART - SANDOVAL",
//     "ROBINSONS EASYMRT - FRIENDSHIP ANGELES",
//     "ROBINSONS IBA, ZAMBALES (.50)",
//     "ROBINSONS - LA UNION",
//     "ROBINSONS - NEPOMALL ANGELES 1",
//     "ROBINSONS PLACE - ABUCAY TACLOBAN",
//     "ROBINSONS PLACE - ANGELES",
//     "ROBINSONS PLACE - ANTIPOLO",
//     "ROBINSONS PLACE - BUTUAN",
//     "ROBINSONS PLACE - CAGAYAN DE ORO",
//     "ROBINSONS PLACE - CAINTA",
//     "ROBINSONS PLACE - CEBU FUENTE",
//     "ROBINSONS PLACE - DASMARINAS",
//     "ROBINSONS PLACE - DUMAGUETE (CALINDAGAN)",
//     "ROBINSONS PLACE - ERMITA-1",
//     "ROBINSONS PLACE - GALLERIA",
//     "ROBINSONS PLACE - GENERAL SANTOS",
//     "ROBINSONS PLACE - GENERAL TRIAS",
//     "ROBINSONS PLACE - ILIGAN",
//     "ROBINSONS PLACE - ILOILO",
//     "ROBINSONS PLACE - IMUS",
//     "ROBINSONS PLACE - LAS PINAS",
//     "ROBINSONS PLACE - LIMA EXCHANGE",
//     "ROBINSONS PLACE - LIPA",
//     "ROBINSONS PLACE - LOS BAÑOS",
//     "ROBINSONS PLACE - MAGNOLIA",
//     "ROBINSONS PLACE - MALABON",
//     "ROBINSONS PLACE - MALOLOS",
//     "ROBINSONS PLACE - MANDALAGAN BACOLOD",
//     "ROBINSONS PLACE - METROEAST",
//     "ROBINSONS PLACE - NAGA",
//     "ROBINSONS PLACE - ORMOC",
//     "ROBINSONS PLACE - PALAWAN",
//     "ROBINSONS PLACE - PAMPANGA",
//     "ROBINSONS PLACE - PANGASINAN",
//     "ROBINSONS PLACE - ROXAS",
//     "ROBINSONS PLACE - SANTIAGO",
//     "ROBINSONS PLACE - SILANG",
//     "ROBINSONS PLACE - STA ROSA",
//     "ROBINSONS PLACE - TACLOBAN",
//     "ROBINSONS PLACE - TAGUM",
//     "ROBINSONS PLACE - TARLAC",
//     "ROBINSONS PLACE - GAPAN",
//     "ROBINSONS PLACE - JARO ILOILO",
//     "ROBINSONS STA. CRUZ",
//     "ROBINSONS TUGUEGARAO",
//     "THE MARKET PLACE - MAGALLANES",
//     "THE MARKETPLACE - SHANGRI-LA",
//     "THE MARKETPALCE - TOMAS MORATO",
//     "SHOPWISE - ALABANG",
//     "SHOPWISE - AMIGO",
//     "SHOPWISE - ANTIPOLO",
//     "SHOPWISE - ARANETA CUBAO",
//     "SHOPWISE - BATANGAS",
//     "SHOPWISE - CDOC",
//     "SHOPWISE - CIRCUIT",
//     "SHOPWISE - IMUS",
//     "SHOPWISE - LANCASTER",
//     "SHOPWISE - MAKATI",
//     "SHOPWISE - MAMBALING",
//     "SHOPWISE - PACITA",
//     "SHOPWISE - SAN FERNANDO",
//     "SHOPWISE - STA.ROSA (PASEO)",
//     "SHOPWISE - SUCAT",
//     "SHOPWISE EXPRESS - Q. AVE",
//     "SOUTH - GROCERS BF",
//     "SOUTH BRENT",
//     "SOUTH LIPA",
//     "SOUTH SUPERMARKET - ALABANG FILINVEST",
//     "SOUTH SUPERMARKET - MARIKINA",
//     "SOUTH SUPERMARKET - PAMPANGA",
//     "SOUTH SUPERMARKET - PASIG",
//     "SOUTH SUPERMARKET - STO. TOMAS",
//     "SOUTH SUPERMARKET - VALENZUELA",
//     "SOUTH SUPERMARKET - LOS BANOS",
//     "SOUTH SUPERMARKET - MALOLOS",
//     "SOUTH SUPERMARKET - PASEO STA ROSA",
//     "SUPER 8 - ALABANG",
//     "SUPER 8 - ANGELES",
//     "SUPER 8 - ANGONO",
//     "SUPER 8 - ANTIPOLO",
//     "SUPER 8 - BACLARAN",
//     "SUPER 8 - BAGONG SILANG",
//     "SUPER 8 - BAGUMBAYAN",
//     "SUPER 8 - BALANGA",
//     "SUPER 8 - BALINTAWAK",
//     "SUPER 8 - BALIUAG",
//     "SUPER 8 - BINAN",
//     "SUPER 8 - BINANGONAN",
//     "SUPER 8 - BLUMENTRITT",
//     "SUPER 8 - CAA LAS PINAS",
//     "SUPER 8 - CABUYAO",
//     "SUPER 8 - CAINTA",
//     "SUPER 8 - CAMARIN",
//     "SUPER 8 - COGEO",
//     "SUPER 8 - COMMONWEALTH",
//     "SUPER 8 - DASMARINAS",
//     "SUPER 8 - ERMIN GARCIA",
//     "SUPER 8 - FARMERS",
//     "SUPER 8 - GAGALANGIN",
//     "SUPER 8 - GEN. T VALENZUELA",
//     "SUPER 8 - GMA",
//     "SUPER 8 - GUADALUPE",
//     "SUPER 8 - GUAGUA",
//     "SUPER 8 - HAGONOY",
//     "SUPER 8 - HULONG DUHAT",
//     "SUPER 8 - JACKMAN",
//     "SUPER 8 - KARUHATAN",
//     "SUPER 8 - LA HUERTA",
//     "SUPER 8 - LAS PINAS",
//     "SUPER 8 - LIBERTAD",
//     "SUPER 8 - LIPA",
//     "SUPER 8 - LITEX",
//     "SUPER 8 - MAKATI",
//     "SUPER 8 - MALIBAY",
//     "SUPER 8 - MALOLOS",
//     "SUPER 8 - MANAOAG",
//     "SUPER 8 - MARULAS",
//     "SUPER 8 - MASINAG",
//     "SUPER 8 - MOLAVE",
//     "SUPER 8 - MOLINO",
//     "SUPER 8 - MORONG",
//     "SUPER 8 - MUNTINLUPA",
//     "SUPER 8 - NAPINDAN",
//     "SUPER 8 - NOVA 2",
//     "SUPER 8 - ORTIGAS EXT. CAINTA",
//     "SUPER 8 - P. BURGOS",
//     "SUPER 8 - PACO",
//     "SUPER 8 - PRITIL",
//     "SUPER 8 - PULILAN",
//     "SUPER 8 - RECTO",
//     "SUPER 8 - ROSARIO",
//     "SUPER 8 - ROSARIO 2",
//     "SUPER 8 - SAN JOAQUIN",
//     "SUPER 8 - SAN JUAN",
//     "SUPER 8 - SAN PABLO",
//     "SUPER 8 - SAN PEDRO",
//     "SUPER 8 - SAPANG PALAY",
//     "SUPER 8 - SHAW",
//     "SUPER 8 - SIGNAL (FTI)",
//     "SUPER 8 - STA MARIA",
//     "SUPER 8 - STA ROSA",
//     "SUPER 8 - SUCAT 2",
//     "SUPER 8 - TANAY",
//     "SUPER 8 - TANDANG SORA",
//     "SUPER 8 - TARLAC 2",
//     "SUPER 8 - TATALON",
//     "SUPER 8 - TAYTAY 1",
//     "SUPER 8 - TAYTAY 2",
//     "SUPER 8 - TINAJEROS",
//     "SUPER 8 - TRECE",
//     "SUPER 8 - URDANETA",
//     "THE MARKET PLACE - METLIVE",
//     "THE MARKET PLACE - PARQAL",
//     "THE MARKETPLACE - 30TH",
//     "THE MARKETPLACE - ALPHALAND",
//     "THE MARKETPLACE - ANTIPOLO",
//     "THE MARKETPLACE - AYALA",
//     "THE MARKETPLACE - AYALA ALABANG",
//     "THE MARKETPLACE - BAGUIO",
//     "THE MARKETPLACE - BANAWA",
//     "THE MARKETPLACE - BGC",
//     "THE MARKETPLACE - CDOC",
//     "THE MARKETPLACE - CENTURY",
//     "THE MARKETPLACE - CORINTHIAN",
//     "THE MARKETPLACE - EASTBAY",
//     "THE MARKETPLACE - EASTWOOD",
//     "THE MARKETPLACE - FESTIVE WALK",
//     "THE MARKETPLACE - GALLERIA SELECTION CEBU",
//     "THE MARKETPLACE - GATEWAY",
//     "THE MARKETPLACE - GREENBELT",
//     "THE MARKETPLACE - GROOVE",
//     "THE MARKETPLACE - KATIPUNAN",
//     "THE MARKETPLACE - MAKATI",
//     "THE MARKETPLACE - OAKRIDGE",
//     "THE MARKETPLACE - P.GUEVARRA",
//     "THE MARKETPLACE - PASEO DE ROXAS",
//     "THE MARKETPLACE - ROCKWELL",
//     "THE MARKETPLACE - SAN ANTONIO",
//     "THE MARKETPLACE - SANTOLAN",
//     "THE MARKETPLACE - TWO CENTRAL",
//     "THE MARKETPLACE - UPTOWN",
//     "THE MARKETPLACE - MAGNOLIA",
//     "THE MARKETPLACE - WESTBORROUGH",
//     "ULTRAMEGA - ANTIPOLO",
//     "ULTRAMEGA - ARAYAT",
//     "ULTRAMEGA - ARITAO",
//     "ULTRAMEGA - BAGONG SILANG",
//     "ULTRAMEGA - BALAGTAS",
//     "ULTRAMEGA - BALIBAGO",
//     "ULTRAMEGA - BALIUAG BAYAN",
//     "ULTRAMEGA - BALIUAG HIGHWAY",
//     "ULTRAMEGA - CABUYAO MAMATID",
//     "ULTRAMEGA - CANDABA",
//     "ULTRAMEGA - CANLUBANG 1",
//     "ULTRAMEGA - CANLUBANG 2",
//     "ULTRAMEGA - CORDON",
//     "ULTRAMEGA - DEPARO",
//     "ULTRAMEGA - GAGALANGIN",
//     "ULTRAMEGA - GEN. TRIAS",
//     "ULTRAMEGA - GUAGUA",
//     "ULTRAMEGA - IFUGAO",
//     "ULTRAMEGA - LEMERY",
//     "ULTRAMEGA - MADDELA ISABELA",
//     "ULTRAMEGA - MONTALBAN",
//     "ULTRAMEGA - MUNTINLUPA",
//     "ULTRAMEGA - NAIC",
//     "ULTRAMEGA - NOVALICHES",
//     "ULTRAMEGA - PADRE GARCIA",
//     "ULTRAMEGA - PALIPARAN",
//     "ULTRAMEGA - ROSARIO",
//     "ULTRAMEGA - SAN MATEO",
//     "ULTRAMEGA - SAN MATEO ISABELA",
//     "ULTRAMEGA - SAN MIGUEL",
//     "ULTRAMEGA - SANGANDAAN",
//     "ULTRAMEGA - SAPANG PALAY",
//     "ULTRAMEGA - TAGAYTAY",
//     "ULTRAMEGA - TAGUIG",
//     "ULTRAMEGA - TANAUAN",
//     "ULTRAMEGA - TANAY",
//     "ULTRAMEGA - TARLAC",
//     "ULTRAMEGA - TUTUBAN",
//     "WALTERMART - CANDELARIA",
//     "WALTERMART SUPERMARKET, INC. - ALTARAZA",
//     "WALTERMART SUPERMARKET, INC. - ANTIPOLO",
//     "WALTERMART SUPERMARKET, INC. - BACOOR",
//     "WALTERMART SUPERMARKET, INC. - BALANGA BATAAN",
//     "WALTERMART SUPERMARKET, INC. - BALAYAN",
//     "WALTERMART SUPERMARKET, INC. - BALIUAG",
//     "WALTERMART SUPERMARKET, INC. - BATANGAS",
//     "WALTERMART SUPERMARKET, INC. - BEL-AIR",
//     "WALTERMART SUPERMARKET, INC. - BICUTAN",
//     "WALTERMART SUPERMARKET, INC. - CABANATUAN",
//     "WALTERMART SUPERMARKET, INC. - CABUYAO",
//     "WALTERMART SUPERMARKET, INC. - CALOOCAN",
//     "WALTERMART SUPERMARKET, INC. - CAPAS",
//     "WALTERMART SUPERMARKET, INC. - CARMONA",
//     "WALTERMART SUPERMARKET, INC. - CONCEPCION",
//     "WALTERMART SUPERMARKET, INC. - DASMA",
//     "WALTERMART SUPERMARKET, INC. - E.ROD",
//     "WALTERMART SUPERMARKET, INC. - GAPAN",
//     "WALTERMART SUPERMARKET, INC. - GEN. TRIAS",
//     "WALTERMART SUPERMARKET, INC. - GUIGUINTO",
//     "WALTERMART SUPERMARKET, INC. - IMUS",
//     "WALTERMART SUPERMARKET, INC. - JUNCTION",
//     "WALTERMART SUPERMARKET, INC. - LOS BANOS",
//     "WALTERMART SUPERMARKET, INC. - MAKATI",
//     "WALTERMART SUPERMARKET, INC. - MAKILING",
//     "WALTERMART SUPERMARKET, INC. - MALOLOS",
//     "WALTERMART SUPERMARKET, INC. - MUNTINLUPA WEST",
//     "WALTERMART SUPERMARKET, INC. - NASUGBU",
//     "WALTERMART SUPERMARKET, INC. - NORTH EDSA",
//     "WALTERMART SUPERMARKET, INC. - PAMPANGA",
//     "WALTERMART SUPERMARKET, INC. - PANIQUI",
//     "WALTERMART SUPERMARKET, INC. - PASAY",
//     "WALTERMART SUPERMARKET, INC. - PLARIDEL",
//     "WALTERMART SUPERMARKET, INC. - SAN JOSE",
//     "WALTERMART SUPERMARKET, INC. - SAN PASCUAL",
//     "WALTERMART SUPERMARKET, INC. - STA MARIA",
//     "WALTERMART SUPERMARKET, INC. - STA. CRUZ",
//     "WALTERMART SUPERMARKET, INC. - STA. ROSA",
//     "WALTERMART SUPERMARKET, INC. - SUBIC ZAMBALES",
//     "WALTERMART SUPERMARKET, INC. - SUCAT",
//     "WALTERMART SUPERMARKET, INC. - TAGAYTAY",
//     "WALTERMART SUPERMARKET, INC. - TALAVERA",
//     "WALTERMART SUPERMARKET, INC. - TANAUAN",
//     "WALTERMART SUPERMARKET, INC. - TAYTAY",
//     "WALTERMART SUPERMARKET, INC. - TRECE MAR",
//     "WALTERMART SUPERMARKET, INC. - VISAYAS AVE",
//     "CAPITAL CASUNTINGAN",
//     "CAPITAL DANAO",
//     "CAPITAL MACTAN",
//     "CAPITAL SRP",
//     "CAPITAL SVM BASAK",
//     "CAPITAL SVM T.PADILLA",
//     "CAPITAL TISA",
//     "FISHER FRESH SHOP -FISHERFOODS CORP",
//     "FISHER RETAIL, INC. - MALABON",
//     "FRIENDSHIP SUPERMARKET INC.",
//     "GAISANO SOUTH COLON",
//     "GRAND BALAMBAN",
//     "GRAND CARCAR",
//     "GRAND CORDOVA",
//     "GRAND DUMANJUG",
//     "GRAND LILOAN",
//     "GRAND MACTAN",
//     "GRAND MANDAUE NORTH",
//     "GRAND MINGLANILLA",
//     "GRAND MOALBOAL",
//     "GRAND TABUNOK",
//     "GRAND TALAMBAN",
//     "HI-TOP SUPERMARKET -AURORA BLVD.",
//     "HI-TOP SUPERMARKET -Q.AVE.",
//     "MAGIC ALAMINOS -MG-5",
//     "MAGIC BAYAMBANG -MG-22",
//     "MAGIC BINMALEY -MG-10",
//     "MAGIC CLUB -MG-4",
//     "MAGIC LINGAYEN -MG-8",
//     "MAGIC MALASIQUE -MG-17",
//     "MAGIC MALL -MGM-3",
//     "MAGIC MALL SANCARLOS",
//     "MAGIC MANAOAG -MG-12",
//     "MAGIC MANGALDAN -MG-7",
//     "MAGIC MANGATAREM -MG-21",
//     "MAGIC POZZORUBIO -MG-19",
//     "MAGIC SAN CARLOS -MG-6",
//     "MAGIC SAN JOSE 2 -MG-16A",
//     "MAGIC SAN JOSE -MG-16",
//     "MAGIC TAYUG -MG-18",
//     "MAGIC VILLASIS -MG-9",
//     "MAGIC ZAMBALES -MG-20",
//     "magicmall Annex",
//     "PIONEER CENTER",
//     "SAVEMORE - EMALL",
//     "SAVEMORE - PARKMALL",
//     "SAVEWISE LINGAYEN",
//     "SAVEWISE MALASIQUI",
//     "SAVEWISE POZORRUBIO",
//     "SAVEWISE ROSALES",
//     "SAVEWISE TAYUG",
//     "SM CONSOLACION",
//     "SM HYPER JMALL",
//     "SM HYPER LAPULAPU",
//     "SM INSULAR",
//     "SM MACTAN",
//     "SM MARIBAGO",
//     "SM SEA SIDE CITY",
//     "STA. LUCIA EAST SUPERMARKET",
//     "STA. LUCIA EAST SUPERMARKET -PHASE 3",
//     "SUPER MAGIC -MG-3",
//     "TROPICAL HUT -BF HOMES",
//     "TROPICAL HUT -FTI TAGUIG",
//   ]);
//   const [delistedCountsCurrentWeek, setDelistedCountsCurrentWeek] =
//     React.useState({});
//   const [inventoryCount, setInventoryCount] = React.useState({});
//   const [notCarriedCount, setNotCarriedCount] = React.useState({});
//   const [selectedBranch, setSelectedBranch] = React.useState(null); // Branch for the modal
//   const [users, setUsers] = React.useState([]); // Users to display in the modal
//   const [open, setOpen] = React.useState(false); // Modal open state
//   const [delistedSkus, setDelistedSkus] = React.useState({});
//   const [skuCount, setSkuCount] = React.useState({
//     V1: 0,
//     V2: 0,
//     V3: 0,
//   });

//   const SKUS = {
//     V1: [
//       "BENG BENG CHOCOLATE 12 X 10 X 26.5G",
//       "BENG BENG SHARE IT 16 X 95G",
//       "CAL CHEESE 10X20X8.5G",
//       "CAL CHEESE 20 X 10 X 20G",
//       "CAL CHEESE 20 X 20 X 8.5G",
//       "CAL CHEESE 60 X 48G",
//       "CAL CHEESE 60X35G",
//       "CAL CHEESE 60X53.5G",
//       "CAL CHEESE CHOCO 20 X 10 X 20.5G",
//       "CAL CHEESE CHOCO 60 X 48G",
//       "DANISA BUTTER COOKIES 12X454G",
//       "MALKIST CAPPUCCINO 30X10X18G PH",
//       "MALKIST CHOCOLATE 30X10X18G",
//       "ROMA Cream Crackers",
//       "SUPERSTAR TRIPLE CHOCOLATE 12 X10 X 18G",
//       "VALMER CHOCOLATE 12X10X54G",
//       "VALMER SANDWICH CHOCOLATE 12X10X36G",
//       "WAFELLO BUTTER CARAMEL 20.5G X 10 X 20",
//       "WAFELLO BUTTER CARAMEL 48G X 60",
//       "WAFELLO CHOCOLATE 21G X 10 X 20",
//       "WAFELLO CHOCOLATE 48G X 60",
//       "WAFELLO COCO CRÈME 48G X 60",
//       "WAFELLO COCO CREME 60X35G",
//       "WAFELLO COCO CREME 60X53.5G",
//       "WAFELLO COCONUT CRÈME 20.5G X 10 X 20",
//       "WAFELLO CREAMY VANILLA 60X48G PH",
//       "WAFELLO CREAMY VANILLA 20X10X20.5G PH",
//       "FRES APPLE PEACH 24 X 50 X 3G",
//       "FRES BARLEY MINT 24X50X3G",
//       "FRES CHERRY CANDY, 24 X 50 X 3G",
//       "FRES CHERRY JAR, 12X 200 X 3G",
//       "FRES GRAPE CANDY, 24 X 50 X 3G",
//       "FRES GRAPE JAR, 12 X 200 X 3G",
//       "FRES MINT BARLEY JAR 12X200X3G",
//       "FRES MIXED CANDY JAR 12 X 600G",
//       "KOPIKO CAPPUCCINO CANDY 24X175G",
//       "KOPIKO COFFEE CANDY 24X175G",
//       "KOPIKO COFFEE CANDY JAR 6X560G",
//       "MALKIST SWEET GLAZED 12X10X28G PH",
//       "MALKIST BARBECUE 12X10X28G PH",
//       "WOW PASTA CARBONARA",
//       "WOW PASTA SPAGHETTI",
//     ],
//     V2: [
//       "Kopiko Blanca hanger 24x10x30g",
//       "Kopiko Blanca Twinpack 12 X 10 X 2 X 29G",
//       "KOPIKO BLANCA, BAG 8 X 30 X 30G",
//       "KOPIKO BLANCA, POUCH 24 X 10 X 30G",
//       "Kopiko Brown Promo Twin 12 x 10 x 53g",
//       "Kopiko Brown Coffee Bag 8x30x27.5g",
//       "Kopiko Black 3 in One Promo Twin 12 x 10 x 2 x 30g",
//       "Kopiko Black 3 in One Hanger 24 x 10 x 30g",
//       "ENERGEN VANILLA HANGER 24 X 10 X 40G",
//       "Kopiko Brown Coffee hg 27.5g 24x10x27.5g",
//       "Kopiko Brown Coffee Pouch 24x10x27.5g",
//       "KOPIKO BLACK 3-IN-1 BAG 8 X 30 X 30G",
//       "KOPIKO BLACK 3-IN-1 POUCH 24 X 10 X 30G",
//       "KOPIKO BLACK 3IN1 TWINPACK 12X10X2X28G",
//       "Kopiko Cappuccino Bag 8x30x25g",
//       "Kopiko Cappuccino Hanger 24 x 10 x 25g",
//       "Kopiko Cappuccino Pouch 24x10x25g",
//       "Kopiko Double Cups 24 x 10 x 36g",
//       "Kopiko L.A. Coffee hanger 24x10x25g",
//       "Kopiko LA Coffee Pouch 24x10x25g",
//       "Energen Chocolate Bag 8x30x40g",
//       "ENERGEN CHOCOLATE HANGER 24 X 10 X 40G",
//       "Energen Chocolate Pouch 24x10x40g",
//       "Energen Vanilla Bag 8x30x40g",
//       "Energen Vanilla Pouch 24x10x40g",
//       "Energen Pandesal Mate 24 x 10 x 30g",
//       "ENERGEN CHAMPION 12X10X2X35G PH",
//       "Energen Champion NBA Hanger 24 x 10 x 35g",
//       "Energen Champion NBA TP 15 x 8 x 2 x30g ph",
//       "Kopiko Creamy Caramelo 12 x (10 x 2) x 25g",
//       "Toracafe White and Creamy 12 X (10 X 2) X 26G",
//       "Kopiko Cafe Mocha TP 12X10X(2X25.5G) PH",
//       "ENERGEN CHAMPION 40X345G",
//       "KOPIKO VOLCANIC DRIP- JAVA 24X10X8G PH",
//       "KOPIKO VOLCANIC DRIP - MANDHELING 24X10X8G PH",
//       "KOPIKO VOLCANIC DRIP - TORAJA 24X10X8G PH",
//     ],
//     V3: [
//       "KOPIKO LUCKY DAY 24BTL X 180ML",
//       "Le Minerale 12x1500ml",
//       "Le Minerale 24x330ml",
//       "Le Minerale 24x600ml",
//       "LE MINERALE 4 X 5000ML",
//     ],
//   };

//   // const getToday = () => {
//   //   const today = new Date();
//   //   return today.toISOString().split("T")[0]; // Returns date in YYYY-MM-DD format
//   // };

//   const getWeekRange = () => {
//     const today = new Date(); // Automatically uses local timezone
//     const dayOfWeek = today.getDay();

//     // Calculate the most recent Friday
//     const lastFriday = new Date(today);
//     lastFriday.setDate(today.getDate() - ((dayOfWeek + 1) % 7)); // Adjust to last Friday

//     // Determine the "active" week based on today
//     const activeFriday = new Date(lastFriday);
//     if (dayOfWeek >= 5) {
//       activeFriday.setDate(lastFriday.getDate() + 7);
//     }

//     // Calculate display range for the previous week (activeFriday - 7 days)
//     const displayStartDate = new Date(activeFriday);
//     displayStartDate.setDate(activeFriday.getDate() - 7); // Previous week's Friday

//     const displayEndDate = new Date(displayStartDate);
//     displayEndDate.setDate(displayStartDate.getDate() + 6); // Previous week's Thursday

//     // Format dates for display range (e.g., Dec 14-20)
//     const formatDate = (date) => {
//       const options = { month: "short", day: "2-digit" };
//       return date.toLocaleDateString("en-PH", options).replace(" ", "");
//     };

//     // Data range for fetching records (activeFriday to activeFriday + 6 days)
//     const startDate = new Date(activeFriday);
//     startDate.setHours(0, 0, 0, 0); // Start of the active Friday (midnight)

//     const endDate = new Date(activeFriday);
//     endDate.setDate(activeFriday.getDate() + 6); // Active Friday + 6 (end of the week)
//     endDate.setHours(23, 59, 59, 999); // End of the active week (just before midnight)

//     // Return formatted display range and start/end date for backend in ISO format
//     return {
//       displayRange: `${formatDate(displayStartDate)}-${formatDate(
//         displayEndDate
//       )}`, // Previous week's range
//       startDate: startDate.toISOString().split("T")[0], // Start date in ISO format (e.g., 2024-12-20)
//       endDate: endDate.toISOString().split("T")[0], // End date in ISO format (e.g., 2024-12-26)
//     };
//   };

//   // Update the delisted SKUs state when an SKU's status changes
//   const updateDelistedSkuState = (skuStatusChange) => {
//     const { branch, skuStatus } = skuStatusChange;

//     // If SKU is delisted, add it to the delisted count for that branch
//     if (skuStatus === "Delisted") {
//       setDelistedSkus((prevState) => ({
//         ...prevState,
//         [branch]: (prevState[branch] || 0) + 1,
//       }));
//     } else if (skuStatus !== "Delisted") {
//       // If SKU is no longer delisted, subtract from the count
//       setDelistedSkus((prevState) => ({
//         ...prevState,
//         [branch]: Math.max((prevState[branch] || 0) - 1, 0), // Prevent going below zero
//       }));
//     }
//   };

//   // Test
//   console.log(getWeekRange());

//   const fetchInventoryCount = async () => {
//     const { startDate, endDate } = getWeekRange(); // Current week's date range
//     const data = { startDate, endDate };

//     try {
//       const response = await axios.post(
//         "https://towi-react.onrender.com/filter-date-range",
//         data
//       );

//       const inventoryData = response.data.data;
//       const filteredInventoryData = inventoryData.filter((item) => {
//         const itemDate = new Date(item.date);
//         return itemDate >= new Date(startDate) && itemDate <= new Date(endDate); // Filter for current week
//       });

//       const carriedCounts = {};
//       const notCarriedCounts = {};
//       const delistedCountsCumulative = { ...delistedSkus }; // Persistent delisted counts

//       filteredInventoryData.forEach((item) => {
//         const branch = item.accountNameBranchManning;

//         // "Carried" count
//         if (item.status === "Carried") {
//           carriedCounts[branch] = (carriedCounts[branch] || 0) + 1;
//         }

//         // "Not Carried" count
//         if (item.status === "Not Carried") {
//           notCarriedCounts[branch] = (notCarriedCounts[branch] || 0) + 1;
//         }

//         // Cumulative "Delisted" count
//         if (item.status === "Delisted") {
//           delistedCountsCumulative[branch] =
//             (delistedCountsCumulative[branch] || 0) + 1; // Increment cumulative
//         }
//       });

//       // Ensure all branches are accounted for
//       branches.forEach((branch) => {
//         carriedCounts[branch] = carriedCounts[branch] || 0;
//         notCarriedCounts[branch] = notCarriedCounts[branch] || 0;
//         delistedCountsCumulative[branch] =
//           delistedCountsCumulative[branch] || delistedSkus[branch] || 0;
//       });

//       // Update state for cumulative and current week counts
//       setInventoryCount(carriedCounts);
//       setNotCarriedCount(notCarriedCounts);
//       setDelistedSkus(delistedCountsCumulative); // Persist cumulative delisted counts
//     } catch (error) {
//       console.error("Error fetching inventory count:", error);
//     }
//   };

//   const rows = branches
//     .filter((accountNameBranchManning) => {
//       const loggedInBranch = localStorage.getItem("accountNameBranchManning");
//       if (!loggedInBranch) {
//         console.error("No branch information found for the logged-in admin.");
//         return false;
//       }
//       const allowedBranches = loggedInBranch
//         .split(",")
//         .map((branch) => branch.trim());
//       return allowedBranches.includes(accountNameBranchManning);
//     })
//     .map((accountNameBranchManning, index) => {
//       const cumulativeDelistedCount =
//         delistedSkus[accountNameBranchManning] || 0; // Cumulative delisted counts
//       const totalSkuCount =
//         skuCount.V1 + skuCount.V2 + skuCount.V3 - cumulativeDelistedCount; // Use cumulative subtraction
//       const notCarriedCountValue =
//         notCarriedCount[accountNameBranchManning] || 0;

//       return {
//         id: index + 1,
//         branchName: accountNameBranchManning,
//         count: inventoryCount[accountNameBranchManning] || 0,
//         totalSkus: totalSkuCount, // Reflect cumulative delisted count adjustment
//         totalNC: notCarriedCountValue,
//         date: getWeekRange().displayRange,
//       };
//     });

//   // Fetch inventory count on component mount
//   React.useEffect(() => {
//     fetchInventoryCount();
//   }, []);

//   const fetchUsersByBranch = async (branch) => {
//     try {
//       // Set the selected branch to display it in the modal header
//       setSelectedBranch(branch);

//       const loggedInBranch = localStorage.getItem("accountNameBranchManning");
//       if (!loggedInBranch) {
//         console.error("No branch information found for the logged-in admin.");
//         return;
//       }

//       const branches = loggedInBranch.split(",").map((b) => b.trim());

//       // Sending the branch info in the POST request to backend
//       const response = await axios.post(
//         "https://towi-react.onrender.com/get-users-by-branch",
//         {
//           branches,
//         }
//       );

//       const users = response.data.users;
//       console.log("Received users from the backend:", users);

//       const filteredUsers = users.filter((user) => {
//         // Determine which branches the user has access to
//         const userBranches = Array.isArray(user.accountNameBranchManning)
//           ? user.accountNameBranchManning
//           : user.accountNameBranchManning.split(",").map((b) => b.trim());

//         console.log("user branches:", userBranches, "Selected Branch:", branch);

//         return userBranches.includes(branch); // Ensure matching branch
//       });

//       console.log("Filtered users based on branch:", filteredUsers);

//       const uniqueUsers = [
//         ...new Map(
//           users.map((user) => [`${user._id}-${user.name}`, user])
//         ).values(),
//       ];

//       console.log("Unique users after filtering:", uniqueUsers);

//       // Set the filtered and unique users to state
//       setUsers(uniqueUsers);

//       // Open the modal to show the users for the selected branch
//       setOpen(true);
//     } catch (error) {
//       console.error("Error fetching users:", error);
//     }
//   };

//   React.useEffect(() => {
//     fetchInventoryCount(); // Fetch data when the component mounts
//     const totalSKUs = {
//       V1: SKUS.V1.length,
//       V2: SKUS.V2.length,
//       V3: SKUS.V3.length,
//     };
//     setSkuCount(totalSKUs);
//   }, []);

//   const decrementSkuCount = (category) => {
//     setSkuCount((prevCount) => ({
//       ...prevCount,
//       [category]: prevCount[category] > 0 ? prevCount[category] - 1 : 0,
//     }));
//   };

//   console.log("Branches:", branches);
//   console.log("Inventory Count:", inventoryCount);
//   console.log("Delisted SKUs:", delistedSkus);
//   console.log("Rows Data:", rows);

//   const columns = [
//     { field: "id", headerName: "#", width: 75, headerClassName: "bold-header" },
//     {
//       field: "branchName",
//       headerName: "ACCOUNT BRANCH",
//       width: 200,
//       headerClassName: "bold-header",
//     },
//     {
//       field: "count",
//       headerName: "CARRIED COUNT (WEEKLY)",
//       width: 250,
//       headerClassName: "bold-header",
//     },
//     //new table Total Not Carried
//     {
//       field: "totalNC",
//       headerName: "NOT CARRIED COUNT (WEEKLY)",
//       width: 320,
//       headerClassName: "bold-header",
//     },

//     {
//       field: "totalSkus",
//       headerName: "TOTAL SKUS",
//       width: 250,
//       headerClassName: "bold-header",
//     },
//     {
//       field: "date",
//       headerName: "WEEK'S COVERED",
//       width: 250,
//       headerClassName: "bold-header",
//     },
//     {
//       field: "viewUsers",
//       headerName: "MERCHANDISERS",
//       width: 160,
//       headerClassName: "bold-header",
//       renderCell: (params) => (
//         <Button
//           variant="contained"
//           onClick={() => fetchUsersByBranch(params.row.branchName)}
//           style={{ backgroundColor: "#4caf50", color: "#ffffff" }} // Green color with white text
//         >
//           View
//         </Button>
//       ),
//     },
//   ];

//   return (
//     <div className="attendance">
//       <Topbar />
//       <Box sx={{ display: "flex", flexDirection: { xs: "column", md: "row" } }}>
//         <Sidebar />
//         <Box
//           sx={{
//             flexGrow: 1,
//             padding: { xs: "10px", sm: "20px" },
//             maxWidth: "100%",
//             overflow: "auto",
//             backgroundColor: "#52B788",
//           }}
//         >
//           {/* Controls Section */}
//           <Stack
//             direction={{ xs: "column", md: "row" }}
//             spacing={2}
//             sx={{ marginBottom: "20px" }}
//           >
//             {/* Add buttons or filters here if required */}
//           </Stack>

//           {/* Responsive DataGrid */}
//           <Box
//             sx={{
//               height: "100%",
//               width: "100%",
//               maxHeight: "80vh",
//               marginTop: 2,
//               overflow: "hidden",
//               "& .MuiDataGrid-root": {
//                 backgroundColor: "#fff",
//               },
//             }}
//           >
//             <DataGrid
//               rows={rows}
//               columns={columns}
//               initialState={{
//                 pagination: {
//                   paginationModel: { page: 0, pageSize: 100 },
//                 },
//               }}
//               slots={{
//                 toolbar: GridToolbar,
//               }}
//               slotProps={{
//                 toolbar: {
//                   showQuickFilter: true,
//                   printOptions: { disableToolbarButton: true },
//                 },
//               }}
//               disableColumnFilter
//               disableColumnSelector
//               disableRowSelectionOnClick
//               pageSizeOptions={[5, 10, 20, 30, 50, 100]}
//               getRowId={(row) => row.id}
//             />
//           </Box>

//           {/* Responsive Modal */}
//           <Modal open={open} onClose={() => setOpen(false)}>
//             <Box
//               sx={{
//                 padding: 4,
//                 backgroundColor: "white",
//                 margin: { xs: "10% auto", md: "5% auto" },
//                 width: { xs: "90%", sm: "70%", md: "50%" },
//                 boxShadow: 24,
//                 borderRadius: 2,
//                 display: "flex",
//                 flexDirection: "column",
//                 alignItems: "center",
//               }}
//             >
//               <Typography
//                 variant="h6"
//                 sx={{ marginBottom: 2, textAlign: "center" }}
//               >
//                 Merchandiser for {selectedBranch}
//               </Typography>
//               <ul style={{ padding: 0, listStyle: "none", width: "100%" }}>
//                 {users.length > 0 ? (
//                   users
//                     .filter((user) => {
//                       const userBranches = Array.isArray(
//                         user.accountNameBranchManning
//                       )
//                         ? user.accountNameBranchManning
//                         : user.accountNameBranchManning
//                             .split(",")
//                             .map((b) => b.trim());

//                       return userBranches.includes(selectedBranch); // Filter by selected branch
//                     })
//                     .map((user) => (
//                       <li
//                         key={`${user._id}-${user.firstName}-${user.lastName}`}
//                         style={{
//                           padding: "10px",
//                           borderBottom: "1px solid #ddd",
//                           textAlign: "center",
//                         }}
//                       >
//                         {`${user.firstName} ${user.lastName}`}
//                       </li>
//                     ))
//                 ) : (
//                   <Typography textAlign="center" color="textSecondary">
//                     No users available for this branch.
//                   </Typography>
//                 )}
//               </ul>
//               <Button
//                 onClick={() => setOpen(false)}
//                 variant="contained"
//                 sx={{
//                   backgroundColor: "rgb(33, 148, 29)",
//                   color: "white",
//                   marginTop: 3,
//                   "&:hover": { backgroundColor: "rgb(33, 148, 29)" },
//                 }}
//               >
//                 Close
//               </Button>
//             </Box>
//           </Modal>
//         </Box>
//       </Box>
//     </div>
//   );
// }
